In [1]:
import pandas as pd
import numpy as np

In [2]:
df_test=pd.read_csv("..\datasets_original\hospitalizaciones_test.csv",sep=",")
df_train=pd.read_csv("..\datasets_original\hospitalizaciones_train.csv",sep=",")
df_test["Stay (in days)"]=np.nan

In [3]:
df_train['Stay (in days)'] = np.where(df_train['Stay (in days)']<8, 0, 1)

In [4]:
print(df_train.isna().sum())

Available Extra Rooms in Hospital    0
Department                           0
Ward_Facility_Code                   0
doctor_name                          0
staff_available                      0
patientid                            0
Age                                  0
gender                               0
Type of Admission                    0
Severity of Illness                  0
health_conditions                    0
Visitors with Patient                0
Insurance                            0
Admission_Deposit                    0
Stay (in days)                       0
dtype: int64


In [5]:
print(df_test.isna().sum())

Available Extra Rooms in Hospital        0
Department                               0
Ward_Facility_Code                       0
doctor_name                              0
staff_available                          0
patientid                                0
Age                                      0
gender                                   0
Type of Admission                        0
Severity of Illness                      0
health_conditions                        0
Visitors with Patient                    0
Insurance                                0
Admission_Deposit                        0
Stay (in days)                       90000
dtype: int64


In [6]:
for i in range (15):
 print(df_train[df_train.columns[i]].unique())

[ 4  2  7  3  5 10  6  1 21  8 11 13  9 14 24  0 12 20]
['gynecology' 'anesthesia' 'TB & Chest disease' 'radiotherapy' 'surgery']
['D' 'B' 'E' 'F' 'A' 'C']
['Dr Sophia' 'Dr Olivia' 'Dr Mark' 'Dr John' 'Dr Sarah' 'Dr Sam'
 'Dr Nathan' 'Dr Simon' 'Dr Isaac']
[ 0  2  8  7 10  5  9  3  6  4  1]
[33070 34808 44577 ... 40881 51342 63598]
['41-50' '31-40' '21-30' '71-80' '11-20' '51-60' '61-70' '81-90' '91-100'
 '0-10']
['Female' 'Male' 'Other']
['Trauma' 'Urgent' 'Emergency']
['Extreme' 'Minor' 'Moderate']
['Diabetes' 'Heart disease' 'None' 'Other' 'Asthama' 'High Blood Pressure']
[ 4  2  3 11  9  6  8 12  5  1 14  7 13 10 22 18  0 16 20 21 19 23 15 24
 17 30 32 25]
['Yes' 'No']
[2966.408696 3554.835677 5624.733654 ... 3816.99421  3841.577491
 4329.046412]
[1 0]


In [7]:
for i in range (15):
 print(df_test[df_test.columns[i]].unique())

[ 3  2  4  5  1  9  6 10 13 11 24 20  7 14 12  0 21  8]
['gynecology' 'TB & Chest disease' 'radiotherapy' 'anesthesia' 'surgery']
['F' 'E' 'A' 'D' 'B' 'C']
['Dr Olivia' 'Dr John' 'Dr Sam' 'Dr Sarah' 'Dr Sophia' 'Dr Nathan'
 'Dr Mark' 'Dr Isaac' 'Dr Simon']
[10  4  7  1  6  5  8  0  9  3  2]
[  2858  65657  45598 ...  75642 118184  33937]
['21-30' '51-60' '71-80' '41-50' '31-40' '0-10' '61-70' '11-20' '81-90'
 '91-100']
['Female' 'Other' 'Male']
['Trauma' 'Urgent' 'Emergency']
['Moderate' 'Extreme' 'Minor']
['Other' 'Asthama' 'None' 'Diabetes' 'Heart disease' 'High Blood Pressure']
[ 2  3  4  8  6 13 14  5  9  1 10  7 12 23 11 19 22  0 17 32 15 24 18 16
 20 21 25 30]
['No' 'Yes']
[4749.640225 4122.261324 5459.067882 ... 5456.930075 4694.127772
 4713.868519]
[nan]


In [8]:
print("duplicados en df_test: ",len(df_test)-len(df_test.drop_duplicates()))
print("duplicados en df_train: ",len(df_train)-len(df_train.drop_duplicates()))

duplicados en df_test:  0
duplicados en df_train:  0


In [9]:
df_train=pd.get_dummies(df_train)
df_test=pd.get_dummies(df_train)


In [10]:
df_train_stay=df_train["Stay (in days)"]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_test)
StandardScaler()
lista_columnas_completa=[]
for n in df_test.columns:
    lista_columnas_completa.append(n)
df_test=scaler.transform(df_test)
df_test=pd.DataFrame(df_test,columns=lista_columnas_completa)
lista_columnas_completa=[]
for n in df_train.columns:
    lista_columnas_completa.append(n)
scaler.fit(df_train)
df_train=scaler.transform(df_train)
df_train=pd.DataFrame(df_train,columns=lista_columnas_completa)

df_train["Stay (in days)"]=df_train_stay
df_test["Stay (in days)"]=np.nan

In [12]:
print(df_train.corr().nlargest(5,"Stay (in days)")["Stay (in days)"].append(df_train.corr().nsmallest(4,"Stay (in days)")["Stay (in days)"]))

Stay (in days)             1.000000
doctor_name_Dr Mark        0.133455
Department_anesthesia      0.130680
Age_31-40                 -0.169099
doctor_name_Dr Sam        -0.237977
Department_radiotherapy   -0.288060
doctor_name_Dr Sam        -0.237977
Age_31-40                 -0.169099
Department_anesthesia      0.130680
Name: Stay (in days), dtype: float64


C:\Users\Lautaro\AppData\Local\Temp\ipykernel_11732\1740225458.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df_train.corr().nlargest(5,"Stay (in days)")["Stay (in days)"].append(df_train.corr().nsmallest(4,"Stay (in days)")["Stay (in days)"]))


In [11]:
df_train=df_train[["doctor_name_Dr Mark","Department_anesthesia","Department_radiotherapy","doctor_name_Dr Sam","Age_31-40","Stay (in days)"]]
print(df_train.head(5))
df_test=df_test[["doctor_name_Dr Mark","Department_anesthesia","Department_radiotherapy","doctor_name_Dr Sam","Age_31-40","Stay (in days)"]]
print(df_test.head(5))

   doctor_name_Dr Mark  Department_anesthesia  Department_radiotherapy  \
0            -0.327841              -0.311432                -0.450346   
1            -0.327841              -0.311432                -0.450346   
2            -0.327841              -0.311432                -0.450346   
3            -0.327841              -0.311432                -0.450346   
4             3.050262               3.210973                -0.450346   

   doctor_name_Dr Sam  Age_31-40  Stay (in days)  
0           -0.371973  -0.593395               1  
1           -0.371973   1.685218               1  
2           -0.371973  -0.593395               0  
3           -0.371973   1.685218               1  
4           -0.371973  -0.593395               1  
   doctor_name_Dr Mark  Department_anesthesia  Department_radiotherapy  \
0            -0.327841              -0.311432                -0.450346   
1            -0.327841              -0.311432                -0.450346   
2            -0.327841     

In [34]:
df_train.to_csv("df_train_mod.csv",index=False)
df_test.to_csv("df_test_mod.csv",index=False)